MAIN = tarefa-1-12558547.f
BINARY = tarefa-1-12558547.exe
UTIL = tarefa-1-graf-1-12558547.gp tarefa-1-graf-2-12558547.gp

all:
	f77 $(MAIN) -o $(BINARY)

run:
	./$(BINARY)
	
	gnuplot $(UTIL)