MAIN = tarefa-5-12558547.f
BINARY = tarefa-5-12558547.f.exe
UTIL = tarefa-5-graf-1-12558547.gp tarefa-5-graf-2-12558547.gp

all:
	f77 $(MAIN) -o $(BINARY)

run:
	./$(BINARY)
	
	gnuplot $(UTIL)