MAIN = tarefa-6-12558547.f
BINARY = tarefa-6-12558547.exe
UTIL = tarefa-6-graf-1-12558547.gp tarefa-6-graf-2-12558547.gp

all:
	f77 $(MAIN) -o $(BINARY)

run:
	./$(BINARY)
	
	gnuplot $(UTIL)